spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63792}
    cache:
      type: redis
      redis:
        time-to-live: PT60M
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@localhost:27017/offers
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

offer:
  http:
    client:
      nofluffjobs:
        connectionTimeout: 1000
        port: 443
        readTimeout: 5000
        uri: https://nofluffjobs.com/api/posting
      pracujpl:
        connectionTimeout: 1000
        port: 443
        readTimeout: 5000
        uri: https://it.pracuj.pl/praca/

http:
  offers:
    scheduler:
      request:
        delay: PT3H

scheduling:
  enabled: true

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: job-offers-backend